"""
BuyerHunter V2 — Intent & Query Planning Schemas

Structured output models for the Intent Analyzer and Hybrid Query Planner.
"""

from pydantic import BaseModel, Field


class SearchIntent(BaseModel):
    """
    Structured intent extracted from a raw user query.

    Example: "Palm Oil Buyers India" yields:
        product="palm oil", business_type="buyer",
        geography=None (nationwide), confidence=0.95
    """
    raw_query: str = Field(description="Original user query string")
    product: str = Field(description="Primary product/commodity (normalized)")
    product_synonyms: list[str] = Field(
        default_factory=list,
        description="Alternative names for the product (e.g., ['CPO', 'RBD palm olein'])",
    )
    business_type: str = Field(
        description="Extracted business role: buyer, manufacturer, distributor, etc."
    )
    business_type_synonyms: list[str] = Field(default_factory=list)
    geography_state: str | None = Field(
        default=None, description="Target state if specified"
    )
    geography_city: str | None = Field(
        default=None, description="Target city if specified"
    )
    geography_nationwide: bool = Field(
        default=True, description="True if no specific geography was given"
    )
    query_type: str = Field(
        description="Classification: product_buyer, industry_search, service_search, import_export, general"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence in intent extraction accuracy"
    )


class StructuredQuery(BaseModel):
    """
    A single generated search query ready for a crawler adapter.

    Produced by the Hybrid Query Planner as part of a QueryPlanResult.
    """
    query_string: str = Field(description="The actual search query to run")
    source: str = Field(description="Target crawler source (indiamart, justdial, etc.)")
    priority: int = Field(ge=1, le=10, description="Priority: 10=highest")
    target_state: str | None = None
    target_city: str | None = None
    intent_label: str = Field(
        default="", description="Human-readable label: 'palm oil buyer in Gujarat'"
    )
    generation_method: str = Field(
        description="'deterministic' or 'ai_expanded'"
    )


class QueryPlanResult(BaseModel):
    """
    Complete output of the Hybrid Query Planner.

    Contains the structured intent plus all generated queries split by source.
    """
    intent: SearchIntent
    deterministic_queries: list[StructuredQuery] = Field(
        default_factory=list,
        description="Queries generated by the deterministic matrix (80%)"
    )
    ai_expanded_queries: list[StructuredQuery] = Field(
        default_factory=list,
        description="Queries generated by the AI planner fallback (20%)"
    )
    total_queries: int = Field(default=0, description="Total across both sources")
    sources_covered: list[str] = Field(
        default_factory=list, description="Distinct crawler sources targeted"
    )
    states_covered: list[str] = Field(
        default_factory=list, description="Distinct states in generated queries"
    )
